[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=9.2"]
build-backend = "setuptools.build_meta"

[project]
name = "musescore-manager"
description = "Tool for managing Musescore files"
readme = "README.md"
authors = [
    { name = "Jongbin Jung", email = "jungjongbin86@gmail.com" }
]
dynamic = ["version"]
requires-python = ">=3.11"

dependencies = [
    "pydantic>=2,<3",
    "typer>=0.21.1",
]

[project.scripts]
msm = "msm.main:app"

[project.optional-dependencies]
all = [
    "musescore-manager[gcs]",
    "musescore-manager[notion]",
    "musescore-manager[s3]",
]
gcs = [
  "google-api-python-client",
  "google-auth-httplib2",
  "google-auth-oauthlib",
]
s3 = [
    "boto3",
]
notion = [
    "notion-client>=2.7.0",
]

[dependency-groups]
dev = [
    "ipython>=9.9.0,<10",
    "musescore-manager[all]",
    "pytest-cov",
    "pytest-mock>=3.6,<4",
    "pytest>=9.0.2,<10",
    "ruff>=0.14.14",
    "setuptools_scm>=8",
]

[tool.pytest.ini_options]
addopts = "--cov=src/msm --cov-report=term:skip-covered"
asyncio_mode = "auto"
minversion = "9.0"
testpaths = [
    "tests",
]

[tool.ruff]
line-length = 120
respect-gitignore = true
src = [
    "src",
    "tests",
]

[tool.ruff.lint]
extend-select = [
    "I",
]
ignore = [
    "E501",
]

[tool.ruff.lint.per-file-ignores]

# Do not enforce usage in init files
"__init__.py" = [
    "E402",
    "F401",
]

[tool.ruff.format]
indent-style = "space"
quote-style = "double"
